language: cpp
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-5
      - g++-5
      - clang-3.6
script:
  - cd examples
  - mkdir build; cd build
  - cmake ..; make
  - cd ../../tests/gtest
  - mkdir build; cd build
  - cmake ..; make
  - cd ../..
  - mkdir build; cd build
  - cmake ..; make
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
