language: cpp
sudo: required
install: sudo apt-get install python
script: cd examples; mkdir build; cd build; cmake ..; make; cd ../../tests/gtest; mkdir build; cd build; cmake ..; make; cd ../..; mkdir build; cd build; cmake ..; make
compiler:
  - gcc
  - clang
os: linux
