language: cpp
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-5
      - g++-5
      - clang-3.6
script:
  - mkdir build; cd build; cmake ..
  - cd examples; make
  - cd ../../tests/gtest; mkdir build; cd build; cmake ..; make
  - cd ../../../build/tests; make
  - ./unit_tests
compiler:
  - gcc
  - clang
os:
  - osx
  - linux
branches:
  only:
    - master
